version: '3.8'
services:
  gradio_app:
    build: .
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - vectordb
    restart: always

  vectordb:
    image: chromadb/chroma:latest
    volumes:
      - vectordb_data:/chroma/index
    restart: always

volumes:
  vectordb_data:

